server:
  port: 9000

spring:
  application:
    name: config-service

  profiles:
    active: dev, secret

  cloud:
    config:
      server:
        git:
          uri: git@github.com-mac:Hong-mae/spring-msa-prj-config.git
          clone-on-start: true
