server:
  port: 8088

spring:
  application:
    name: api-gateway

  profiles:
    active: dev, secret

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

      discovery:
        locator:
          enabled: true # ✨ 이거 추가하면 Eureka 서비스 자동 라우팅도 됨

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
