server:
  port: 8088

spring:
  application:
    name: api-gateway

  discovery:
    locator:
      enabled: true

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
