spring:
  application:
    name: user-service

  profiles:
    active: dev, secret

  config:
    import: optional:configserver:http://hongmae:Fu89PavCOD@localhost:9000

jwt:
  issuer: ${jwt.issure}
  secretKey: ${jwt.secretKey}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka

logging:
  level:
    org.springframework.web: DEBUG
